vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: /uploads/articles
            upload_destination: '%kernel.project_dir%/public/media/cache/carre/uploads/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
