
indexAPI:
    path: /api-index
    controller: App\Controller\ApiController::index
    methods: [GET,POST,DELETE]
index:
    path: /
    controller: App\Controller\BlogController::index
    methods: [GET,POST,DELETE]


api:
    path: /api
    controller: App\Controller\ApiController::api
    methods: [GET,POST,DELETE]


post:
    path: /post/{idPost}
    controller: App\Controller\BlogController::post
    methods: [GET]

newpost:
    path: /newPost
    controller: App\Controller\BlogController::newPost
    methods: [GET, POST]

editPost:
    path: /editPost/{idPost<[0-9]+>}
    controller: App\Controller\BlogController::editPost
    methods: [POST, GET]

deletePost:
    path: /deletePost/{idPost<[0-9]+>}
    controller: App\Controller\BlogController::deletePost
    methods: [GET,POST,DELETE]
        

 